---
title: "OPER 782 - Analytic Proposal Review #1"
author: "Matthew Small"
date: "17 January 18"
output: github_document
keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 1

## Provide a short name (either a single word or an acronym) for the analytic you plan     to develop. 

Boots

## Provide a brief title (1-2 sentences)   describing - at the 50,000 foot level - what your analytic does.  Your title should be short and to the point, but should also be clear to an end user.

The analytic takes Defense Manpower Data Center(DMDC) data on troop numbers abroad for active duty military personnel and generates forecasts for the selected country or countries, provides accuracy statistics, a visual depiction of the forecasts including actual observed values, and projected troop numbers for the year or years of interest.  

## Provide a description (2-3 paragraphs) of why this analytic data product will be useful for an end-user.

This analytic will be utilized by USTRANSCOM to better predict USTRANSCOM workload demands in coming years.  The features which my analytic will perform when complete are to import the data, tidy the data in the format popularized by Wickham, group the data by country, branch, order the data by year, convert the data to a zoo/time series object, implement forecast functions, plot the forecasts, provide accuracy metrics, provide forecast values, and confidence intervals for years of interest. The typical end-users for whom this analytic is being developed are analysts at USTRANSCOM/JDPAC.  Important knowledge/skills/abilities an end-user must have in order to utilize the analytic is a knowledge of forecasting techniques such as ARIMA, exponential smoothing, and possibly some dynamic regression models; however, the analytic will provide a basic description of what the model is and its key parameters and terms.

The analytic implements autoregressive integrated moving average (ARIMA) forecasting models, simple exponential smoothing models, Holt models, and forecasting accuracy metrics.  
This analytic is built upon \textbf{R} packages: *forecast, ggplot2 and tidyverse*.  

## How will end-users access your analytic data product?

End-users will access the data analytic product via the internet.  The analytic will be available via the github repository and potentially on the CRAN network.

## Are there any security concerns that need to be addressed?

All data are available from the unclassified, open-source database maintained by DMDC.  There are no security concerns that need to be addressed.  

## Are there any appearance/design constraints that your analytic must adhere to?

There are no appearance/design constraints that the analytic must adhere to, but the goal is to provide a clean design with easy to use graphical user interface.

# Section 2
The following table gives several features which will be addressed in the analytic. Each row in the table represents a column.  Information pertaining to the following points are also provided in each of the columns:

* 2.1.A.	The description of the feature
* 2.1.B.	A rank ordered priority number for this feature
* 2.1.C.	The status of the feature – should be either ‘finished’, ‘in-work’, or ‘not started’
* 2.1.D.	What value will this feature provide to an end-user?
* 2.1.E.	What input(s) must be provided by end-user to perform this feature?
* 2.1.F.	What output(s) will this feature return to the end-user?
* 2.1.G.	What do you envision an end-user will do with the output of this feature? 
* 2.1.H.	Is there sufficient time to deliver this feature prior to the deadline?
* 2.1.I.	Does this feature need to be included in the current version of your analytic or can it be pushed to a future update?

A rank of 1 is deemed most important with higher values being of lesser import.

| Feature           | Description                                                                                                                 | Rank | Status      | Value                                                                                                                                                                                 | Inputs/Outputs                                                                                              | Utilization                                                                                                                                                                                                                       | Sufficient Time? | Current or Future? |
|-------------------|-----------------------------------------------------------------------------------------------------------------------------|------|-------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------|--------------------|
| Download the Data | This feature downloads the data off of the DMDC website                                                                     | 10   | Not Started | This makes the user not have to spend as much time having to download the data.                                                                                                       | Inputs: PDF and/or Microsoft Excel Files Containing Troop ValuesOutputs: R Data Frame Containing Troop Data | Get new DMDC Data                                                                                                                                                                                                                 | Maybe            | Future             |
| Tidy the Data     | This feature tidys the data such that each variable is represented by a column and each observation is represented by a row | 7    | In Progress | This makes the data easy to work with since it is in the format popularized by Wickham                                                                                                | Inputs: R Data Frame in Non-Tidy FormatOutputs: R Data Frame in Tidy Format                                 | Organizes the data in a convenient format                                                                                                                                                                                         | Yes              | Current            |
| Group Data        | This feature groups the data by country and military branch.                                                                | 6    | In Progress | This is valuable in that it allows for forecasts to be disaggregated for future use of forecasting in hopes that disaggregation will improve forecast accuracy.                       | Inputs: R Data Frame in Tidy FormatOutputs: R Data Frame grouped by country and branch.                     | Allows for disaggregated forecasting                                                                                                                                                                                              | Yes              | Current            |
| Order Data        | This feature orders the data in chronological order                                                                         | 4    | In Progress | Ordering the data is necessary for forecasting the data.                                                                                                                              | Inputs: R Data FrameOutputs: R Data Frame                                                                   | Necessary for the end product                                                                                                                                                                                                     | Yes              | Current            |
| Fill Missing Data | This feature fills the missing observations by interpolating between the nearest two points.                                | 8    | In Progress | Filling missing data will allow for forecasting functions to work properly and clearly explains how missing data is being handled.                                                    | Inputs: R Data FrameOutputs: R Data Frame                                                                   | Necessary for the end product                                                                                                                                                                                                     | Yes              | Current            |
| Convert Data      | This feature converts the ordered data into a time series object.                                                           | 5    | In Progress | Converting the data series into a Zoo object in R allows forecasting functions to operate.                                                                                            | Inputs: R Data FrameOutputs:Zoo Object                                                                      | Necessary for the end product                                                                                                                                                                                                     | Yes              | Current            |
| Forecast          | This feature takes the converted data and applies forecasting functions to it.                                              | 1    | In Progress | Forecasting the data utilizing Rob Hyndman's forecast package allows for exponential smoothing, ARIMA, and several other forecasting functions to be implemented.                     | Inputs: Zoo ObjectOutputs: Forecast Object                                                                  | Allows the end-user to generate their desired forecast models.                                                                                                                                                                    | Yes              | Current            |
| Plot Forecasts    | This function takes the forecast and generates plots.                                                                       | 3    | In Progress | Plotting the functions allows the end-user to have a visual depiction of how well the forecasting is predicting new observations.                                                     | Inputs: Forecast ObjectOutputs: Plot (graphical object)                                                     | Allows for user to visualize the forecasts                                                                                                                                                                                        | Yes              | Current            |
| Assess Accuracy   | This function assesses the accuracy of the forecasts.                                                                       | 9    | In Progress | Assessing the accuracy of the forecasts indicates which forecasts are performing well and which are performing poorly.  This will allow the user to select the best performing model. | Inputs: Forecast ObjectOutputs: List of forecast accuracy metrics                                           | The output will enable the user to compare forecasts accuracies in order to determine which forecast is fitting the data best.  This can then be compared to the parsimony of the model to determine which one is most efficient. | Yes              | Current            |
| Provide Values    | This function provides the actual values for the forecast for use in USTRANSCOM Models                                      | 2    | Not Started | By providing the forecasted values, this analytic will enable USTRANSCOM to feed US troop data into its workload demand forecasts.                                                    | Inputs: Forecast ObjectOutputs: Vector                                                                      | Providing values is necessary so that USTRANSCOM can incorporate forecasted values into its workload demand forecast models.                                                                                                      | Yes              | Current            |